/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.23
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "roc-send"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "roc-send"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION VERSION
#endif

enum enum_color { color__NULL = -1, color_arg_auto = 0, color_arg_always, color_arg_never };
enum enum_resampler_backend { resampler_backend__NULL = -1, resampler_backend_arg_auto = 0, resampler_backend_arg_builtin, resampler_backend_arg_speex, resampler_backend_arg_speexdec };
enum enum_resampler_profile { resampler_profile__NULL = -1, resampler_profile_arg_low = 0, resampler_profile_arg_medium, resampler_profile_arg_high };
enum enum_latency_backend { latency_backend__NULL = -1, latency_backend_arg_niq = 0 };
enum enum_latency_profile { latency_profile__NULL = -1, latency_profile_arg_responsive = 0, latency_profile_arg_gradual, latency_profile_arg_intact };

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  unsigned int verbose_min; /**< @brief Increase verbosity level (may be used multiple times)'s minimum occurreces */
  unsigned int verbose_max; /**< @brief Increase verbosity level (may be used multiple times)'s maximum occurreces */
  const char *verbose_help; /**< @brief Increase verbosity level (may be used multiple times) help description.  */
  enum enum_color color_arg;	/**< @brief Set colored logging mode for stderr output (default='auto').  */
  char * color_orig;	/**< @brief Set colored logging mode for stderr output original value given at command line.  */
  const char *color_help; /**< @brief Set colored logging mode for stderr output help description.  */
  const char *list_supported_help; /**< @brief List supported protocols, formats, etc. help description.  */
  char * input_arg;	/**< @brief Input file or device URI.  */
  char * input_orig;	/**< @brief Input file or device URI original value given at command line.  */
  const char *input_help; /**< @brief Input file or device URI help description.  */
  char * io_encoding_arg;	/**< @brief Input device encoding.  */
  char * io_encoding_orig;	/**< @brief Input device encoding original value given at command line.  */
  const char *io_encoding_help; /**< @brief Input device encoding help description.  */
  char * io_latency_arg;	/**< @brief Input device latency, TIME units.  */
  char * io_latency_orig;	/**< @brief Input device latency, TIME units original value given at command line.  */
  const char *io_latency_help; /**< @brief Input device latency, TIME units help description.  */
  char * io_frame_len_arg;	/**< @brief Input frame length, TIME units.  */
  char * io_frame_len_orig;	/**< @brief Input frame length, TIME units original value given at command line.  */
  const char *io_frame_len_help; /**< @brief Input frame length, TIME units help description.  */
  char ** source_arg;	/**< @brief Remote source endpoint to connect to.  */
  char ** source_orig;	/**< @brief Remote source endpoint to connect to original value given at command line.  */
  unsigned int source_min; /**< @brief Remote source endpoint to connect to's minimum occurreces */
  unsigned int source_max; /**< @brief Remote source endpoint to connect to's maximum occurreces */
  const char *source_help; /**< @brief Remote source endpoint to connect to help description.  */
  char ** repair_arg;	/**< @brief Remote repair endpoint to connect to.  */
  char ** repair_orig;	/**< @brief Remote repair endpoint to connect to original value given at command line.  */
  unsigned int repair_min; /**< @brief Remote repair endpoint to connect to's minimum occurreces */
  unsigned int repair_max; /**< @brief Remote repair endpoint to connect to's maximum occurreces */
  const char *repair_help; /**< @brief Remote repair endpoint to connect to help description.  */
  char ** control_arg;	/**< @brief Remote control endpoint to connect to.  */
  char ** control_orig;	/**< @brief Remote control endpoint to connect to original value given at command line.  */
  unsigned int control_min; /**< @brief Remote control endpoint to connect to's minimum occurreces */
  unsigned int control_max; /**< @brief Remote control endpoint to connect to's maximum occurreces */
  const char *control_help; /**< @brief Remote control endpoint to connect to help description.  */
  char ** miface_arg;	/**< @brief IPv4 or IPv6 address of the network interface on which to join the multicast group.  */
  char ** miface_orig;	/**< @brief IPv4 or IPv6 address of the network interface on which to join the multicast group original value given at command line.  */
  unsigned int miface_min; /**< @brief IPv4 or IPv6 address of the network interface on which to join the multicast group's minimum occurreces */
  unsigned int miface_max; /**< @brief IPv4 or IPv6 address of the network interface on which to join the multicast group's maximum occurreces */
  const char *miface_help; /**< @brief IPv4 or IPv6 address of the network interface on which to join the multicast group help description.  */
  const char *reuseaddr_help; /**< @brief Enable SO_REUSEADDR when binding sockets help description.  */
  char * packet_encoding_arg;	/**< @brief Custom network packet encoding.  */
  char * packet_encoding_orig;	/**< @brief Custom network packet encoding original value given at command line.  */
  const char *packet_encoding_help; /**< @brief Custom network packet encoding help description.  */
  char * packet_len_arg;	/**< @brief Network packet length, TIME units.  */
  char * packet_len_orig;	/**< @brief Network packet length, TIME units original value given at command line.  */
  const char *packet_len_help; /**< @brief Network packet length, TIME units help description.  */
  char * fec_encoding_arg;	/**< @brief FEC encoding, 'auto' to auto-detect from network endpoints.  */
  char * fec_encoding_orig;	/**< @brief FEC encoding, 'auto' to auto-detect from network endpoints original value given at command line.  */
  const char *fec_encoding_help; /**< @brief FEC encoding, 'auto' to auto-detect from network endpoints help description.  */
  int fec_block_src_arg;	/**< @brief Number of source packets in FEC block.  */
  char * fec_block_src_orig;	/**< @brief Number of source packets in FEC block original value given at command line.  */
  const char *fec_block_src_help; /**< @brief Number of source packets in FEC block help description.  */
  int fec_block_rpr_arg;	/**< @brief Number of repair packets in FEC block.  */
  char * fec_block_rpr_orig;	/**< @brief Number of repair packets in FEC block original value given at command line.  */
  const char *fec_block_rpr_help; /**< @brief Number of repair packets in FEC block help description.  */
  enum enum_resampler_backend resampler_backend_arg;	/**< @brief Resampler backend (default='auto').  */
  char * resampler_backend_orig;	/**< @brief Resampler backend original value given at command line.  */
  const char *resampler_backend_help; /**< @brief Resampler backend help description.  */
  enum enum_resampler_profile resampler_profile_arg;	/**< @brief Resampler profile (default='medium').  */
  char * resampler_profile_orig;	/**< @brief Resampler profile original value given at command line.  */
  const char *resampler_profile_help; /**< @brief Resampler profile help description.  */
  char * target_latency_arg;	/**< @brief Target latency, TIME units or 'auto' for adaptive mode.  */
  char * target_latency_orig;	/**< @brief Target latency, TIME units or 'auto' for adaptive mode original value given at command line.  */
  const char *target_latency_help; /**< @brief Target latency, TIME units or 'auto' for adaptive mode help description.  */
  char * latency_tolerance_arg;	/**< @brief Maximum deviation from target latency, TIME units.  */
  char * latency_tolerance_orig;	/**< @brief Maximum deviation from target latency, TIME units original value given at command line.  */
  const char *latency_tolerance_help; /**< @brief Maximum deviation from target latency, TIME units help description.  */
  char * start_latency_arg;	/**< @brief Starting target latency in adaptive mode, TIME units.  */
  char * start_latency_orig;	/**< @brief Starting target latency in adaptive mode, TIME units original value given at command line.  */
  const char *start_latency_help; /**< @brief Starting target latency in adaptive mode, TIME units help description.  */
  char * min_latency_arg;	/**< @brief Minimum target latency in adaptive mode, TIME units.  */
  char * min_latency_orig;	/**< @brief Minimum target latency in adaptive mode, TIME units original value given at command line.  */
  const char *min_latency_help; /**< @brief Minimum target latency in adaptive mode, TIME units help description.  */
  char * max_latency_arg;	/**< @brief Maximum target latency in adaptive mode, TIME units.  */
  char * max_latency_orig;	/**< @brief Maximum target latency in adaptive mode, TIME units original value given at command line.  */
  const char *max_latency_help; /**< @brief Maximum target latency in adaptive mode, TIME units help description.  */
  enum enum_latency_backend latency_backend_arg;	/**< @brief Which latency to measure and tune (default='niq').  */
  char * latency_backend_orig;	/**< @brief Which latency to measure and tune original value given at command line.  */
  const char *latency_backend_help; /**< @brief Which latency to measure and tune help description.  */
  enum enum_latency_profile latency_profile_arg;	/**< @brief Latency tuning profile (default='intact').  */
  char * latency_profile_orig;	/**< @brief Latency tuning profile original value given at command line.  */
  const char *latency_profile_help; /**< @brief Latency tuning profile help description.  */
  int prometheus_metrics_port_arg;	/**< @brief Port for prometheus metrics HTTP exposer (default='0').  */
  char * prometheus_metrics_port_orig;	/**< @brief Port for prometheus metrics HTTP exposer original value given at command line.  */
  const char *prometheus_metrics_port_help; /**< @brief Port for prometheus metrics HTTP exposer help description.  */
  int prometheus_niq_latency_buckets_arg;	/**< @brief Number of histogram buckets for NIQ latency metrics (default='100').  */
  char * prometheus_niq_latency_buckets_orig;	/**< @brief Number of histogram buckets for NIQ latency metrics original value given at command line.  */
  const char *prometheus_niq_latency_buckets_help; /**< @brief Number of histogram buckets for NIQ latency metrics help description.  */
  char * prometheus_niq_latency_min_arg;	/**< @brief Minimum NIQ latency bucket boundary, TIME units (default='5ms').  */
  char * prometheus_niq_latency_min_orig;	/**< @brief Minimum NIQ latency bucket boundary, TIME units original value given at command line.  */
  const char *prometheus_niq_latency_min_help; /**< @brief Minimum NIQ latency bucket boundary, TIME units help description.  */
  char * prometheus_niq_latency_max_arg;	/**< @brief Maximum NIQ latency bucket boundary, TIME units (default='50ms').  */
  char * prometheus_niq_latency_max_orig;	/**< @brief Maximum NIQ latency bucket boundary, TIME units original value given at command line.  */
  const char *prometheus_niq_latency_max_help; /**< @brief Maximum NIQ latency bucket boundary, TIME units help description.  */
  int prometheus_e2e_latency_buckets_arg;	/**< @brief Number of histogram buckets for E2E latency metrics (default='100').  */
  char * prometheus_e2e_latency_buckets_orig;	/**< @brief Number of histogram buckets for E2E latency metrics original value given at command line.  */
  const char *prometheus_e2e_latency_buckets_help; /**< @brief Number of histogram buckets for E2E latency metrics help description.  */
  char * prometheus_e2e_latency_min_arg;	/**< @brief Minimum E2E latency bucket boundary, TIME units (default='20ms').  */
  char * prometheus_e2e_latency_min_orig;	/**< @brief Minimum E2E latency bucket boundary, TIME units original value given at command line.  */
  const char *prometheus_e2e_latency_min_help; /**< @brief Minimum E2E latency bucket boundary, TIME units help description.  */
  char * prometheus_e2e_latency_max_arg;	/**< @brief Maximum E2E latency bucket boundary, TIME units (default='200ms').  */
  char * prometheus_e2e_latency_max_orig;	/**< @brief Maximum E2E latency bucket boundary, TIME units original value given at command line.  */
  const char *prometheus_e2e_latency_max_help; /**< @brief Maximum E2E latency bucket boundary, TIME units help description.  */
  int prometheus_jitter_buckets_arg;	/**< @brief Number of histogram buckets for jitter metrics (default='100').  */
  char * prometheus_jitter_buckets_orig;	/**< @brief Number of histogram buckets for jitter metrics original value given at command line.  */
  const char *prometheus_jitter_buckets_help; /**< @brief Number of histogram buckets for jitter metrics help description.  */
  char * prometheus_jitter_min_arg;	/**< @brief Minimum jitter bucket boundary, TIME units (default='100us').  */
  char * prometheus_jitter_min_orig;	/**< @brief Minimum jitter bucket boundary, TIME units original value given at command line.  */
  const char *prometheus_jitter_min_help; /**< @brief Minimum jitter bucket boundary, TIME units help description.  */
  char * prometheus_jitter_max_arg;	/**< @brief Maximum jitter bucket boundary, TIME units (default='200ms').  */
  char * prometheus_jitter_max_orig;	/**< @brief Maximum jitter bucket boundary, TIME units original value given at command line.  */
  const char *prometheus_jitter_max_help; /**< @brief Maximum jitter bucket boundary, TIME units help description.  */
  int prometheus_rtt_buckets_arg;	/**< @brief Number of histogram buckets for RTT metrics (default='100').  */
  char * prometheus_rtt_buckets_orig;	/**< @brief Number of histogram buckets for RTT metrics original value given at command line.  */
  const char *prometheus_rtt_buckets_help; /**< @brief Number of histogram buckets for RTT metrics help description.  */
  char * prometheus_rtt_min_arg;	/**< @brief Minimum RTT bucket boundary, TIME units (default='1ms').  */
  char * prometheus_rtt_min_orig;	/**< @brief Minimum RTT bucket boundary, TIME units original value given at command line.  */
  const char *prometheus_rtt_min_help; /**< @brief Minimum RTT bucket boundary, TIME units help description.  */
  char * prometheus_rtt_max_arg;	/**< @brief Maximum RTT bucket boundary, TIME units (default='100ms').  */
  char * prometheus_rtt_max_orig;	/**< @brief Maximum RTT bucket boundary, TIME units original value given at command line.  */
  const char *prometheus_rtt_max_help; /**< @brief Maximum RTT bucket boundary, TIME units help description.  */
  char * max_packet_size_arg;	/**< @brief Maximum network packet size, SIZE units.  */
  char * max_packet_size_orig;	/**< @brief Maximum network packet size, SIZE units original value given at command line.  */
  const char *max_packet_size_help; /**< @brief Maximum network packet size, SIZE units help description.  */
  char * max_frame_size_arg;	/**< @brief Maximum I/O and processing frame size, SIZE units.  */
  char * max_frame_size_orig;	/**< @brief Maximum I/O and processing frame size, SIZE units original value given at command line.  */
  const char *max_frame_size_help; /**< @brief Maximum I/O and processing frame size, SIZE units help description.  */
  int prof_flag;	/**< @brief Enable self-profiling (default=off).  */
  const char *prof_help; /**< @brief Enable self-profiling help description.  */
  char * dump_arg;	/**< @brief Dump run-time metrics to specified CSV file.  */
  char * dump_orig;	/**< @brief Dump run-time metrics to specified CSV file original value given at command line.  */
  const char *dump_help; /**< @brief Dump run-time metrics to specified CSV file help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int verbose_given ;	/**< @brief Whether verbose was given.  */
  unsigned int color_given ;	/**< @brief Whether color was given.  */
  unsigned int list_supported_given ;	/**< @brief Whether list-supported was given.  */
  unsigned int input_given ;	/**< @brief Whether input was given.  */
  unsigned int io_encoding_given ;	/**< @brief Whether io-encoding was given.  */
  unsigned int io_latency_given ;	/**< @brief Whether io-latency was given.  */
  unsigned int io_frame_len_given ;	/**< @brief Whether io-frame-len was given.  */
  unsigned int source_given ;	/**< @brief Whether source was given.  */
  unsigned int repair_given ;	/**< @brief Whether repair was given.  */
  unsigned int control_given ;	/**< @brief Whether control was given.  */
  unsigned int miface_given ;	/**< @brief Whether miface was given.  */
  unsigned int reuseaddr_given ;	/**< @brief Whether reuseaddr was given.  */
  unsigned int packet_encoding_given ;	/**< @brief Whether packet-encoding was given.  */
  unsigned int packet_len_given ;	/**< @brief Whether packet-len was given.  */
  unsigned int fec_encoding_given ;	/**< @brief Whether fec-encoding was given.  */
  unsigned int fec_block_src_given ;	/**< @brief Whether fec-block-src was given.  */
  unsigned int fec_block_rpr_given ;	/**< @brief Whether fec-block-rpr was given.  */
  unsigned int resampler_backend_given ;	/**< @brief Whether resampler-backend was given.  */
  unsigned int resampler_profile_given ;	/**< @brief Whether resampler-profile was given.  */
  unsigned int target_latency_given ;	/**< @brief Whether target-latency was given.  */
  unsigned int latency_tolerance_given ;	/**< @brief Whether latency-tolerance was given.  */
  unsigned int start_latency_given ;	/**< @brief Whether start-latency was given.  */
  unsigned int min_latency_given ;	/**< @brief Whether min-latency was given.  */
  unsigned int max_latency_given ;	/**< @brief Whether max-latency was given.  */
  unsigned int latency_backend_given ;	/**< @brief Whether latency-backend was given.  */
  unsigned int latency_profile_given ;	/**< @brief Whether latency-profile was given.  */
  unsigned int prometheus_metrics_port_given ;	/**< @brief Whether prometheus-metrics-port was given.  */
  unsigned int prometheus_niq_latency_buckets_given ;	/**< @brief Whether prometheus-niq-latency-buckets was given.  */
  unsigned int prometheus_niq_latency_min_given ;	/**< @brief Whether prometheus-niq-latency-min was given.  */
  unsigned int prometheus_niq_latency_max_given ;	/**< @brief Whether prometheus-niq-latency-max was given.  */
  unsigned int prometheus_e2e_latency_buckets_given ;	/**< @brief Whether prometheus-e2e-latency-buckets was given.  */
  unsigned int prometheus_e2e_latency_min_given ;	/**< @brief Whether prometheus-e2e-latency-min was given.  */
  unsigned int prometheus_e2e_latency_max_given ;	/**< @brief Whether prometheus-e2e-latency-max was given.  */
  unsigned int prometheus_jitter_buckets_given ;	/**< @brief Whether prometheus-jitter-buckets was given.  */
  unsigned int prometheus_jitter_min_given ;	/**< @brief Whether prometheus-jitter-min was given.  */
  unsigned int prometheus_jitter_max_given ;	/**< @brief Whether prometheus-jitter-max was given.  */
  unsigned int prometheus_rtt_buckets_given ;	/**< @brief Whether prometheus-rtt-buckets was given.  */
  unsigned int prometheus_rtt_min_given ;	/**< @brief Whether prometheus-rtt-min was given.  */
  unsigned int prometheus_rtt_max_given ;	/**< @brief Whether prometheus-rtt-max was given.  */
  unsigned int max_packet_size_given ;	/**< @brief Whether max-packet-size was given.  */
  unsigned int max_frame_size_given ;	/**< @brief Whether max-frame-size was given.  */
  unsigned int prof_given ;	/**< @brief Whether prof was given.  */
  unsigned int dump_given ;	/**< @brief Whether dump was given.  */

} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief the description string of the program */
extern const char *gengetopt_args_info_description;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);

extern const char *cmdline_parser_color_values[];  /**< @brief Possible values for color. */
extern const char *cmdline_parser_resampler_backend_values[];  /**< @brief Possible values for resampler-backend. */
extern const char *cmdline_parser_resampler_profile_values[];  /**< @brief Possible values for resampler-profile. */
extern const char *cmdline_parser_latency_backend_values[];  /**< @brief Possible values for latency-backend. */
extern const char *cmdline_parser_latency_profile_values[];  /**< @brief Possible values for latency-profile. */


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
